all:
	#gcc mypng.c -I ~/retrowrite/mytest/libpng/libpng -L ~/retrowrite/mytest/libpng/libpng/.libs -lpng -lz -lm -static -o mypng 
	gcc mypng.c -I ~/retrowrite/mytest/libpng/libpng -L. -lpng -lz -lm -static -o mypng 
	#gcc mypng.c  -lpng -o mypng 